# Generated by Django 5.0.6 on 2024-05-23 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_nilaiakhirmodel_pengajuansekolahmodel_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PengajuanSMKModel',
        ),
    ]
