# Generated by Django 5.0.6 on 2024-05-25 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pengajuansmkmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='nama',
            new_name='nama_sekolah',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='nip',
            new_name='npsn',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='golongan',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='umur',
        ),
    ]
