# Generated by Django 5.0.6 on 2024-05-25 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_nama_customuser_nama_sekolah_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='nama_sekolah',
            new_name='nama',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='npsn',
            new_name='nip',
        ),
    ]
