# Generated by Django 5.0.6 on 2024-05-25 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0007_customuser_nama_sekolah_customuser_npsn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='nama_sekolah',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='npsn',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='customuser_groups', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nip',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='customuser_permissions', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
