# Generated by Django 5.0.6 on 2024-05-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_customuser_nama_sekolah_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengajuansekolahmodel',
            name='JumlahGuru',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pengajuansekolahmodel',
            name='JumlahKelas',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temporarypengajuansekolah',
            name='JumlahGuru',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temporarypengajuansekolah',
            name='JumlahKelas',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
